### ISSUE TITLE
Revise label for `Collection Captions Text`

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#15]
We should be more descriptive with this, rather than keeping it to text. I'm thinking `label` might work here, or maybe `Page Link Label`. 2 instances of it:
- ```
  id: listing_caption_text
  label: Collection Captions Text
  ```
- ```
  id: listing_caption_text_font
  label: Collection Captions Text
  ```

**Comment by MaximSiebert** [comment]
Revised to 

```
- id: listing_caption_text
  label: Page Link Label
```

and 

```
- id: listing_caption_text_font
  label: Page Link Label Font
```
