### ISSUE TITLE
iPad: Header can't be shown if you scroll back to the top of page

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#16]
- Open site
- Scroll down, note the menu disappears as expected
- Scroll back to the top
- Note that the menu disappears when one has returned to the top of the document and can't be opened if one is at the top of the page

**Comment by MaximSiebert** [comment]
I think I know what was causing this issue but don't have an ipad on hand to test. Please check if this is still happening and close the issue if not!
