### ISSUE TITLE
Galleries: Update hash style

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#22]
- `http://garry-ing.format-staging.com/work#images-5` -> `http://garry-ing.format-staging.com/work#5`
- We should stick to just having the number index

**Comment by MaximSiebert** [comment]
'images' is the name of the group, so by default it does images-#, I can change 'images' but I can't remove it, so I could do something like `#id-2`. This is default fancybox functionality, I don't think they allow you to change the structure.

**Comment by MaximSiebert** [comment]
e-, or on load #10
