### ISSUE TITLE
Galleries, Captions: Update style for captions in slideshow

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#23]
![screen shot 2018-03-02 at 2 34 36 pm](https://user-images.githubusercontent.com/227587/36918137-dac30ccc-1e26-11e8-9bbc-aaf690f75ec9.png)
We haven't taken a good look at how captions are being treated in the slideshow. A few thoughts:
- Left align the block, like how it is presented in the gallery grid
- Set a width/max-width so that we avoid really long line-lengths
- Move the block further up so that it's not close to the bottom of the viewport

**Comment by MaximSiebert** [comment]
I think the best solution is to simply remove the captions in the lightbox - I'm realizing people will often have long captions like this and would rather not cover the image. Let me know if this solution works for you!
