### ISSUE TITLE
Blog Posts: Overlay lightbox image not visible after clicking on thumbnail

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#3]
- Navigate to http://lvh.me:9293/blog/travelling-to-nyc
- Click on a thumbnail to invoke the lightbox
- Note the image does not load
- From a brief inspection: We use Fancybox for blog image overlays, which might be conflicting with the version we're using in galleries

**Comment by MaximSiebert** [comment]
Fixed, but missing `fancybox_overlay.png`

**Comment by garrying** [comment]
missing `fancybox_overlay.png` is expected on themebuilder. feel free to close if the colliding styles/js has been resolved.
