### ISSUE TITLE
Store, Index: Up scaled product image

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#4]
We have yet to roll out improvements to our Store layouts, and that includes retina store images. We should stick to the native resolution for now, 200x200.

![screen shot 2018-02-23 at 4 12 59 pm](https://user-images.githubusercontent.com/227587/36617288-d7f86888-18b4-11e8-8daf-e1dc5b26c78f.png)

**Comment by MaximSiebert** [comment]
I removed my `max-width: none !important` which shrunk the size back, but for some reason the thumbnails are still showing at 233px wide. It looks like some of the 'sales' page css you guys have is screwing with this. It's using important so there's no way for me to override either.

```
.product-list .product {
    color: #9B9B9B;
    display: inline-block;
    margin: 0 2% 30px 2% !important;
    padding: 0 !important;
    text-align: center;
    width: 20.5% !important;
    word-wrap: break-word;
    vertical-align: top;
}
```

Removing `padding: 0 !important` makes the images go down to under 200px

**Comment by garrying** [comment]
@MaximSiebert I think I was able to track this down to this general `img` declaration:
```
img {
  width: 100%;
  display: block;
  height: auto; }
```
The declaration you mentioned is fine as it's coming from our shared stylesheets. Also not that we treat the image as an `inline-block` to center it relative the item title.
