### ISSUE TITLE
Site Image Logo: Tall logos are distorted

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#6]
<img width="333" alt="screen shot 2018-02-26 at 3 43 24 pm" src="https://user-images.githubusercontent.com/227587/36694286-e5948e96-1b0b-11e8-9dc2-e3f4eeab6ae9.png">

- Original: `https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png`
- You'll need to manual type `image` into the `Logo Type` variable in order to switch into the image logo

**Comment by MaximSiebert** [comment]
there was `max-height: 100px;` leftover from the boilerplate css, removed this which solved the issue.
